LESSONS = [
    ('01', 'Python basics', 'print(), comments, expressions'),
    ('02', 'Variables', 'names, assignment, mutability'),
    ('03', 'Numbers', 'int, float, arithmetic'),
    ('04', 'Strings', 'text, slicing, formatting'),
    ('05', 'Booleans', 'truth values and comparisons'),
    ('06', 'Conditionals', 'if, elif, else'),
    ('07', 'Loops', 'for, while, break, continue'),
    ('08', 'Collections', 'list, tuple, set, dict'),
    ('09', 'Functions', 'parameters, return, scope'),
    ('10', 'Exceptions', 'try, except, else, finally'),
    ('11', 'Modules', 'import and packages'),
    ('12', 'Files and paths', 'pathlib and safe persistence'),
    ('13', 'Classes', 'objects, methods, inheritance'),
    ('14', 'Dataclasses', 'structured state'),
    ('15', 'Iterators', 'iter and next'),
    ('16', 'Generators', 'yield and generator expressions'),
    ('17', 'Decorators', 'higher-order functions'),
    ('18', 'Context managers', 'with and resource lifecycles'),
    ('19', 'Typing', 'annotations, generics, protocols'),
    ('20', 'Pattern matching', 'match and case'),
    ('21', 'Async Python', 'async, await, asyncio'),
    ('22', 'Testing', 'assertions, unittest and pytest concepts'),
    ('23', 'Standard library', 'collections, itertools, functools and more'),
    ('24', 'Python data model', 'dunder methods and protocols'),
    ('25', 'Capstone', 'build a complete interactive Pypet feature'),
]
