package com.odelly.pypet;

import android.app.Activity;
import android.graphics.Color;
import android.view.Gravity;
import android.widget.*;

/** Real in-world building activities. Buildings perform gameplay, not description-only dialogs. */
public final class BuildingActivityView {
    private BuildingActivityView() {}
    private static LinearLayout root(Activity a,String title,String subtitle){LinearLayout r=new LinearLayout(a);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(28,24,28,24);TextView h=new TextView(a);h.setText(title);h.setTextSize(27);h.setTextColor(Color.DKGRAY);h.setGravity(Gravity.CENTER);r.addView(h);TextView s=new TextView(a);s.setText(subtitle);s.setTextSize(15);s.setGravity(Gravity.CENTER);s.setPadding(0,8,0,20);r.addView(s);return r;}
    private static Button button(Activity a,LinearLayout r,String text){Button b=new Button(a);b.setText(text);b.setAllCaps(false);r.addView(b,new LinearLayout.LayoutParams(-1,-2));return b;}
    private static void back(Activity a,LinearLayout r){Button b=button(a,r,"🌎 Return to PyPet World");b.setOnClickListener(v->LivingWorldView.show(a));}
    private static void status(Activity a,TextView out){out.setText("❤️ Health "+PetEvolutionManager.health(a)+"   🍎 Hunger "+PetEvolutionManager.hunger(a)+"   😊 Happiness "+PetEvolutionManager.happiness(a)+"\n🧼 Hygiene "+PetCareSystem.hygiene(a));}
    public static void home(Activity a){PetCareSystem.tick(a);LinearLayout r=root(a,"🏠 HOME","Care for your pet and keep its everyday needs balanced.");TextView stats=new TextView(a);stats.setTextSize(17);r.addView(stats);status(a,stats);for(PetEvolutionManager.PetFood f:PetEvolutionManager.foods()){Button b=button(a,r,f.emoji+" Feed "+f.name);b.setOnClickListener(v->{PetEvolutionManager.feed(a,f);status(a,stats);Toast.makeText(a,"Your pet enjoyed "+f.name+".",Toast.LENGTH_SHORT).show();});}Button bath=button(a,r,"🛁 Bathe pet");bath.setOnClickListener(v->{PetCareSystem.bathe(a);status(a,stats);});Button clean=button(a,r,"🧹 Clean up waste");clean.setOnClickListener(v->{PetCareSystem.cleanWaste(a);status(a,stats);});Button care=button(a,r,"❤️ Complete care routine");care.setOnClickListener(v->{PetEvolutionManager.performCare(a);PetEvolutionManager.performRoutine(a);status(a,stats);});back(a,r);a.setContentView(r);}
    public static void market(Activity a){LinearLayout r=root(a,"🛒 MARKET","Choose food for your pet. Every purchase is an actual care action.");TextView stats=new TextView(a);stats.setTextSize(17);r.addView(stats);status(a,stats);for(PetEvolutionManager.PetFood f:PetEvolutionManager.foods()){Button b=button(a,r,f.emoji+" Buy & feed "+f.name+"  •  +"+f.hunger+" hunger");b.setOnClickListener(v->{PetEvolutionManager.feed(a,f);status(a,stats);Toast.makeText(a,"Purchased and served "+f.name+".",Toast.LENGTH_SHORT).show();});}Button inspect=button(a,r,"📊 View pet development");inspect.setOnClickListener(v->Toast.makeText(a,"Development score: "+PetEvolutionManager.balancedDevelopmentScore(a)+" / 100",Toast.LENGTH_SHORT).show());back(a,r);a.setContentView(r);}
    public static void workshop(Activity a){LinearLayout r=root(a,"🔧 WORKSHOP","Build decorations and place your accomplishments in the town.");TextView placed=new TextView(a);placed.setTextSize(16);r.addView(placed);Runnable refresh=()->placed.setText("🏘 Town decorations: "+WorldPlacementManager.all(a).size());refresh.run();String[] ids={"bench","flower_bed","lamp","tree","trophy_stand","garden_sign"};String[] labels={"🪑 Build bench","🌷 Plant flower bed","💡 Build street lamp","🌳 Plant tree","🏆 Build trophy stand","🪧 Build garden sign"};for(int i=0;i<ids.length;i++){final String id=ids[i];final int n=i;Button b=button(a,r,labels[i]);b.setOnClickListener(v->{WorldPlacementManager.place(a,id,-900+n*260,1150,1f,0f);refresh.run();Toast.makeText(a,"Built and placed: "+id,Toast.LENGTH_SHORT).show();});}Button trophy=button(a,r,"🏆 Display accomplishment");trophy.setOnClickListener(v->{WorldPlacementManager.place(a,"achievement_display",0,1400,1f,0f);refresh.run();});back(a,r);a.setContentView(r);}
    public static void park(Activity a){PetCareSystem.tick(a);LinearLayout r=root(a,"🌳 PARK","Play, explore and take a healthy break with your pet.");TextView score=new TextView(a);score.setTextSize(17);score.setGravity(Gravity.CENTER);r.addView(score);Runnable refresh=()->score.setText("😊 Happiness "+PetEvolutionManager.happiness(a)+"\n🎾 Play sessions "+PetEvolutionManager.play(a)+"   🗺 Explorations "+PetEvolutionManager.explore(a));refresh.run();Button play=button(a,r,"🎾 Play in the playground");play.setOnClickListener(v->{PetEvolutionManager.playWith(a);refresh.run();});Button explore=button(a,r,"🦋 Explore the park");explore.setOnClickListener(v->{PetEvolutionManager.performExplore(a);refresh.run();});Button breakBtn=button(a,r,"🌤 Take a healthy break");breakBtn.setOnClickListener(v->{PetEvolutionManager.performRoutine(a);PetCareSystem.tick(a);refresh.run();Toast.makeText(a,"Healthy break completed.",Toast.LENGTH_SHORT).show();});back(a,r);a.setContentView(r);}
    public static void library(Activity a){LinearLayout r=root(a,"📚 LIBRARY","Study and review Python and job-readiness knowledge at your own pace.");TextView progress=new TextView(a);progress.setTextSize(17);progress.setText("Lessons mastered: "+PetEvolutionManager.lessons(a)+"\nSchool sessions: "+PetEvolutionManager.school(a));r.addView(progress);TextView question=new TextView(a);question.setTextSize(19);question.setPadding(0,25,0,15);question.setText("What does len([1, 2, 3]) return?");r.addView(question);String[] choices={"2","3","4","It prints the list"};for(String c:choices){Button b=button(a,r,c);b.setOnClickListener(v->{if(((Button)v).getText().toString().equals("3")){PetEvolutionManager.completeLesson(a);progress.setText("✓ Correct!\nLessons mastered: "+PetEvolutionManager.lessons(a)+"\nSchool sessions: "+PetEvolutionManager.school(a));Toast.makeText(a,"Correct — you explained a Python concept.",Toast.LENGTH_SHORT).show();}else Toast.makeText(a,"Not quite. Review lists and len(), then try again.",Toast.LENGTH_SHORT).show();});}Button next=button(a,r,"🐍 Open hands-on Python Academy");next.setOnClickListener(v->PypetAcademyActivityView.show(a));back(a,r);a.setContentView(r);}
}
