package com.odelly.pypet;

import android.app.Activity;
import android.graphics.Color;
import android.view.Gravity;
import android.widget.*;
import java.util.List;

/** Real in-world activities. Python teaching is intentionally not hosted in ordinary buildings. */
public final class BuildingActivityView {
    private BuildingActivityView() {}
    private static LinearLayout root(Activity a,String title,String subtitle){LinearLayout r=new LinearLayout(a);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(28,24,28,24);ScrollView scroll=new ScrollView(a);scroll.addView(r);TextView h=new TextView(a);h.setText(title);h.setTextSize(27);h.setTextColor(Color.DKGRAY);h.setGravity(Gravity.CENTER);r.addView(h);TextView s=new TextView(a);s.setText(subtitle);s.setTextSize(15);s.setGravity(Gravity.CENTER);s.setPadding(0,8,0,20);r.addView(s);a.setContentView(scroll);return r;}
    private static Button button(Activity a,LinearLayout r,String text){Button b=new Button(a);b.setText(text);b.setAllCaps(false);r.addView(b,new LinearLayout.LayoutParams(-1,-2));return b;}
    private static void back(Activity a,LinearLayout r){Button b=button(a,r,"🌎 Return to PyPet World");b.setOnClickListener(v->LivingWorldView.show(a));}
    private static void completed(Activity a,String id,int coins){int streak=PypetAchievementManager.recordDailyActivity(a);RewardInventory.completeTask(a,"activity_"+id,coins);PypetAchievementManager.awardTrophy(a,"first_step",10);PypetAchievementManager.awardStreakMilestone(a,streak);}
    private static void status(Activity a,TextView out){out.setText("❤️ Health "+PetEvolutionManager.health(a)+"   🍎 Hunger "+PetEvolutionManager.hunger(a)+"   😊 Happiness "+PetEvolutionManager.happiness(a)+"\n🧼 Hygiene "+PetCareSystem.hygiene(a)+"   🪙 "+RewardInventory.coins(a)+" Pypet Coins");}
    /** Compatibility entry only. The actual Home UI is always the three-room care experience. */
    public static void home(Activity a){PetHomeCareView.show(a);}
    public static void market(Activity a){LinearLayout r=root(a,"🛒 MARKET","Earn and spend Pypet Coins on persistent cosmetics for your town.");Button rewards=button(a,r,"🎁 Open Reward Center • optional ads + exclusive World items");rewards.setOnClickListener(v->RewardCenterView.show(a));Button treasures=button(a,r,"✨ Open Treasure Trove • Google Play purchases");treasures.setOnClickListener(v->TreasureStore.show(a));TextView wallet=new TextView(a);wallet.setTextSize(18);r.addView(wallet);Runnable refresh=()->wallet.setText("🪙 Pypet Coins: "+RewardInventory.coins(a)+"   🧺 Owned: "+RewardInventory.count(a));refresh.run();List<RewardCatalog.Item> items=RewardCatalog.all();for(RewardCatalog.Item item:items)if(item.tier.equals("COIN")||item.tier.equals("AD_COIN")){final RewardCatalog.Item x=item;Button b=button(a,r,x.name+" • "+x.priceCoins+" coins\n"+x.description);if(RewardInventory.owns(a,x.id))b.setEnabled(false);b.setOnClickListener(v->{if(RewardInventory.purchase(a,x.id)){WorldPlacementManager.placeUnique(a,x.id,-700+(RewardInventory.count(a)%5)*300,900+(RewardInventory.count(a)/5)*150,1f,0f);completed(a,"purchase_"+x.id,1);refresh.run();b.setEnabled(false);Toast.makeText(a,"Purchased and added to your World.",Toast.LENGTH_SHORT).show();}else Toast.makeText(a,"Earn more Pypet Coins to unlock this item.",Toast.LENGTH_SHORT).show();});}back(a,r);}
    public static void workshop(Activity a){LinearLayout r=root(a,"🔧 WORKSHOP","Build and arrange accomplishments in your town. Objects persist and are kept off roads.");TextView placed=new TextView(a);placed.setTextSize(16);r.addView(placed);Runnable refresh=()->placed.setText("🏘 Decorations: "+WorldPlacementManager.all(a).size()+"\n🏆 Trophies: "+PypetAchievementManager.trophyCount(a));refresh.run();String[] ids={"bench","flower_bed","lamp","tree","trophy_stand","garden_sign"};String[] labels={"🪑 Build bench","🌷 Plant flower bed","💡 Build street lamp","🌳 Plant tree","🏆 Build trophy stand","🪧 Build garden sign"};for(int i=0;i<ids.length;i++){final String id=ids[i];final int n=i;Button b=button(a,r,labels[i]);b.setOnClickListener(v->{WorldPlacementManager.place(a,id,-820+(n%3)*300,760+(n/3)*300,1f,0f);completed(a,"build_"+id,2);if(WorldPlacementManager.all(a).size()>=5)PypetAchievementManager.awardTrophy(a,"world_builder",100);refresh.run();Toast.makeText(a,"Built and placed in your town.",Toast.LENGTH_SHORT).show();});}for(PypetAchievementManager.Trophy t:PypetAchievementManager.trophies())if(PypetAchievementManager.hasTrophy(a,t.id)){final PypetAchievementManager.Trophy trophy=t;Button b=button(a,r,"🏆 Display "+trophy.name);b.setOnClickListener(v->{WorldPlacementManager.setTrophyDisplay(a,trophy.id,true);WorldPlacementManager.placeUnique(a,"trophy_"+trophy.id,-760+(PypetAchievementManager.trophyCount(a)%5)*300,1250,1f,0f);refresh.run();});}back(a,r);}
    public static void park(Activity a){PetCareSystem.tick(a);LinearLayout r=root(a,"🌳 PARK","Play, explore and take healthy breaks with your pet. This is not a Python lesson.");TextView score=new TextView(a);score.setTextSize(17);score.setGravity(Gravity.CENTER);r.addView(score);Runnable refresh=()->score.setText("😊 Happiness "+PetEvolutionManager.happiness(a)+"\n🎾 Play sessions "+PetEvolutionManager.play(a)+"   🗺 Explorations "+PetEvolutionManager.explore(a)+"\n🪙 "+RewardInventory.coins(a)+" Pypet Coins");refresh.run();Button play=button(a,r,"🎾 Play in the playground");play.setOnClickListener(v->{if(!PetEvolutionManager.isHatched(a)){Toast.makeText(a,"🥚 Hatch your egg first.",Toast.LENGTH_SHORT).show();return;}PetEvolutionManager.playWith(a);completed(a,"play",4);refresh.run();});Button explore=button(a,r,"🦋 Explore the park");explore.setOnClickListener(v->{if(!PetEvolutionManager.isHatched(a)){Toast.makeText(a,"🥚 Hatch your egg first.",Toast.LENGTH_SHORT).show();return;}PetEvolutionManager.performExplore(a);completed(a,"explore",4);refresh.run();});Button br=button(a,r,"🌤 Take a healthy break");br.setOnClickListener(v->{if(!PetEvolutionManager.isHatched(a)){Toast.makeText(a,"🥚 Hatch your egg first.",Toast.LENGTH_SHORT).show();return;}PetEvolutionManager.performRoutine(a);PetCareSystem.tick(a);completed(a,"healthy_break",4);refresh.run();Toast.makeText(a,"Healthy break completed.",Toast.LENGTH_SHORT).show();});back(a,r);}
    public static void library(Activity a){LinearLayout r=root(a,"📚 LIBRARY","A quiet reading room for your town. Python instruction and sequential lesson progress live exclusively in PyPet Academy.");TextView note=new TextView(a);note.setTextSize(17);note.setText("📖 This building is for the town, not for learning Python.\n\nVisit 🏫 PyPet Academy whenever you want to learn or continue the curriculum. Academy progress always resumes at the first unfinished lesson and advances one lesson at a time until the final capstone.");note.setPadding(0,12,0,18);r.addView(note);Button academy=button(a,r,"🏫 Go to PyPet Academy");academy.setOnClickListener(v->PypetAcademyActivityView.show(a));Button read=button(a,r,"📚 Browse town books");read.setOnClickListener(v->{RewardInventory.completeTask(a,"library_visit",2);Toast.makeText(a,"📖 You browsed the library. Python lessons remain in Academy.",Toast.LENGTH_SHORT).show();});back(a,r);}
}
