package com.odelly.pypet;

import android.app.Activity;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.view.Gravity;
import android.widget.*;
import java.util.List;

/** Real in-world activities. Opening a building never grants a reward by itself. */
public final class BuildingActivityView {
    private BuildingActivityView() {}
    private static LinearLayout root(Activity a,String title,String subtitle){LinearLayout r=new LinearLayout(a);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(28,24,28,24);ScrollView scroll=new ScrollView(a);scroll.addView(r);TextView h=new TextView(a);h.setText(title);h.setTextSize(27);h.setTextColor(Color.DKGRAY);h.setGravity(Gravity.CENTER);r.addView(h);TextView s=new TextView(a);s.setText(subtitle);s.setTextSize(15);s.setGravity(Gravity.CENTER);s.setPadding(0,8,0,20);r.addView(s);a.setContentView(scroll);return r;}
    private static Button button(Activity a,LinearLayout r,String text){Button b=new Button(a);b.setText(text);b.setAllCaps(false);r.addView(b,new LinearLayout.LayoutParams(-1,-2));return b;}
    private static void back(Activity a,LinearLayout r){Button b=button(a,r,"🌎 Return to PyPet World");b.setOnClickListener(v->LivingWorldView.show(a));}
    private static void completed(Activity a,String id,int coins){int streak=PypetAchievementManager.recordDailyActivity(a);RewardInventory.completeTask(a,"activity_"+id,coins);PypetAchievementManager.awardTrophy(a,"first_step",10);PypetAchievementManager.awardStreakMilestone(a,streak);}
    private static void status(Activity a,TextView out){out.setText("❤️ Health "+PetEvolutionManager.health(a)+"   🍎 Hunger "+PetEvolutionManager.hunger(a)+"   😊 Happiness "+PetEvolutionManager.happiness(a)+"\n🧼 Hygiene "+PetCareSystem.hygiene(a)+"   🪙 "+RewardInventory.coins(a)+" Pypet Coins");}
    public static void home(Activity a){
        PetCareSystem.tick(a);LinearLayout r=root(a,"🏠 HOME","Your pet's home is where care begins. The Hatchery controls the egg → pet lifecycle.");
        TextView stats=new TextView(a);stats.setTextSize(17);r.addView(stats);status(a,stats);
        PetEvolutionManager.Egg egg=PetEvolutionManager.currentEgg(a);
        TextView lifecycle=new TextView(a);lifecycle.setTextSize(16);lifecycle.setGravity(Gravity.CENTER);lifecycle.setPadding(0,12,0,12);lifecycle.setText(PetEvolutionManager.isHatched(a)?"🐾 Your "+egg.lineage+" pet is hatched. Keep caring and learning to evolve it.":egg.emoji+" Your pet is still inside its "+egg.pattern+" egg. Hatch the egg before the pet begins its journey.");r.addView(lifecycle);
        Button hatchery=button(a,r,"🥚 Open Hatchery • Egg → Hatchling → Evolution");hatchery.setOnClickListener(v->PypetHatcheryView.show(a));
        for(PetEvolutionManager.PetFood f:PetEvolutionManager.foods()){Button b=button(a,r,f.emoji+" Feed "+f.name);b.setOnClickListener(v->{if(!PetEvolutionManager.isHatched(a)){Toast.makeText(a,"🥚 Hatch your egg first.",Toast.LENGTH_SHORT).show();return;}PetEvolutionManager.feed(a,f);completed(a,"feed_"+f.id,2);status(a,stats);Toast.makeText(a,"Your pet enjoyed "+f.name+".",Toast.LENGTH_SHORT).show();});}
        Button bath=button(a,r,"🛁 Bathe pet");bath.setOnClickListener(v->{if(!PetEvolutionManager.isHatched(a)){Toast.makeText(a,"🥚 Hatch your egg first.",Toast.LENGTH_SHORT).show();return;}PetCareSystem.bathe(a);completed(a,"bath",3);status(a,stats);});
        Button clean=button(a,r,"🧹 Clean up waste");clean.setOnClickListener(v->{if(!PetEvolutionManager.isHatched(a)){Toast.makeText(a,"🥚 Hatch your egg first.",Toast.LENGTH_SHORT).show();return;}PetCareSystem.cleanWaste(a);completed(a,"clean",3);status(a,stats);});
        Button care=button(a,r,"❤️ Complete care routine");care.setOnClickListener(v->{if(!PetEvolutionManager.isHatched(a)){Toast.makeText(a,"🥚 Hatch your egg first.",Toast.LENGTH_SHORT).show();return;}PetEvolutionManager.performCare(a);PetEvolutionManager.performRoutine(a);completed(a,"care",5);if(PetEvolutionManager.care(a)>=5)PypetAchievementManager.awardTrophy(a,"caring_friend",50);status(a,stats);});
        back(a,r);
    }
    public static void market(Activity a){LinearLayout r=root(a,"🛒 MARKET","Earn and spend Pypet Coins on persistent cosmetics for your town.");Button rewards=button(a,r,"🎁 Open Reward Center • optional ads + exclusive World items");rewards.setOnClickListener(v->RewardCenterView.show(a));Button treasures=button(a,r,"✨ Open Treasure Trove • Google Play purchases");treasures.setOnClickListener(v->TreasureStore.show(a));TextView wallet=new TextView(a);wallet.setTextSize(18);r.addView(wallet);Runnable refresh=()->wallet.setText("🪙 Pypet Coins: "+RewardInventory.coins(a)+"   🧺 Owned: "+RewardInventory.count(a));refresh.run();List<RewardCatalog.Item> items=RewardCatalog.all();for(RewardCatalog.Item item:items)if(item.tier.equals("COIN")||item.tier.equals("AD_COIN")){final RewardCatalog.Item x=item;Button b=button(a,r,x.name+" • "+x.priceCoins+" coins\n"+x.description);if(RewardInventory.owns(a,x.id))b.setEnabled(false);b.setOnClickListener(v->{if(RewardInventory.purchase(a,x.id)){WorldPlacementManager.placeUnique(a,x.id,-700+(RewardInventory.count(a)%5)*300,900+(RewardInventory.count(a)/5)*150,1f,0f);completed(a,"purchase_"+x.id,1);refresh.run();b.setEnabled(false);Toast.makeText(a,"Purchased and added to your World.",Toast.LENGTH_SHORT).show();}else Toast.makeText(a,"Earn more Pypet Coins to unlock this item.",Toast.LENGTH_SHORT).show();});}back(a,r);}
    public static void workshop(Activity a){LinearLayout r=root(a,"🔧 WORKSHOP","Build and arrange accomplishments in your town. Objects persist and are kept off roads.");TextView placed=new TextView(a);placed.setTextSize(16);r.addView(placed);Runnable refresh=()->placed.setText("🏘 Decorations: "+WorldPlacementManager.all(a).size()+"\n🏆 Trophies: "+PypetAchievementManager.trophyCount(a));refresh.run();String[] ids={"bench","flower_bed","lamp","tree","trophy_stand","garden_sign"};String[] labels={"🪑 Build bench","🌷 Plant flower bed","💡 Build street lamp","🌳 Plant tree","🏆 Build trophy stand","🪧 Build garden sign"};for(int i=0;i<ids.length;i++){final String id=ids[i];final int n=i;Button b=button(a,r,labels[i]);b.setOnClickListener(v->{WorldPlacementManager.place(a,id,-820+(n%3)*300,760+(n/3)*300,1f,0f);completed(a,"build_"+id,2);if(WorldPlacementManager.all(a).size()>=5)PypetAchievementManager.awardTrophy(a,"world_builder",100);refresh.run();Toast.makeText(a,"Built and placed in your town.",Toast.LENGTH_SHORT).show();});}for(PypetAchievementManager.Trophy t:PypetAchievementManager.trophies())if(PypetAchievementManager.hasTrophy(a,t.id)){final PypetAchievementManager.Trophy trophy=t;Button b=button(a,r,"🏆 Display "+trophy.name);b.setOnClickListener(v->{WorldPlacementManager.setTrophyDisplay(a,trophy.id,true);WorldPlacementManager.placeUnique(a,"trophy_"+trophy.id,-760+(PypetAchievementManager.trophyCount(a)%5)*300,1250,1f,0f);refresh.run();});}back(a,r);}
    public static void park(Activity a){PetCareSystem.tick(a);LinearLayout r=root(a,"🌳 PARK","A real play and wellbeing routine with your pet.");TextView score=new TextView(a);score.setTextSize(17);score.setGravity(Gravity.CENTER);r.addView(score);Runnable refresh=()->score.setText("😊 Happiness "+PetEvolutionManager.happiness(a)+"\n🎾 Play sessions "+PetEvolutionManager.play(a)+"   🗺 Explorations "+PetEvolutionManager.explore(a)+"\n🪙 "+RewardInventory.coins(a)+" Pypet Coins");refresh.run();Button play=button(a,r,"🎾 Play in the playground");play.setOnClickListener(v->{if(!PetEvolutionManager.isHatched(a)){Toast.makeText(a,"🥚 Hatch your egg first.",Toast.LENGTH_SHORT).show();return;}PetEvolutionManager.playWith(a);completed(a,"play",4);refresh.run();});Button explore=button(a,r,"🦋 Explore the park");explore.setOnClickListener(v->{if(!PetEvolutionManager.isHatched(a)){Toast.makeText(a,"🥚 Hatch your egg first.",Toast.LENGTH_SHORT).show();return;}PetEvolutionManager.performExplore(a);completed(a,"explore",4);refresh.run();});Button br=button(a,r,"🌤 Take a healthy break");br.setOnClickListener(v->{if(!PetEvolutionManager.isHatched(a)){Toast.makeText(a,"🥚 Hatch your egg first.",Toast.LENGTH_SHORT).show();return;}PetEvolutionManager.performRoutine(a);PetCareSystem.tick(a);completed(a,"healthy_break",4);refresh.run();Toast.makeText(a,"Healthy break completed.",Toast.LENGTH_SHORT).show();});back(a,r);}

    public static void library(Activity a){
        LinearLayout r=root(a,"📚 LIBRARY","Study Python before the practice questions. The library is the review room; the Academy is the actual taught lesson sequence.");
        Button academy=button(a,r,"🏫 START / CONTINUE PYTHON LESSONS");academy.setOnClickListener(v->PypetAcademyActivityView.show(a));
        TextView note=new TextView(a);note.setTextSize(15);note.setText("No previous Python knowledge is required. If a question uses a concept you have not learned, open the Academy first. Each correct answer immediately unlocks the next challenge.");note.setPadding(0,8,0,16);r.addView(note);
        final String[] q={"What does len([1, 2, 3]) return?","Which symbol assigns a value to a variable?","Which type represents True or False?","Which keyword starts a conditional?","Which keyword defines a function?","Which collection stores key/value pairs?","What does print() primarily do?","Which loop iterates over items in a collection?","What does return do inside a function?","Which block handles an expected exception?"};
        final String[][] choices={{"2","3","4","The list"},{"=","==","=>","::"},{"bool","text","number","list"},{"if","for","def","class"},{"def","func","function","make"},{"dict","list","tuple","set"},{"Displays a value","Reads a file","Defines a class","Installs Python"},{"for","if","def","try"},{"Sends a value back to the caller","Prints only","Stops Android","Creates a class"},{"try/except","if/else","for/in","def/return"}};
        final int[] correct={1,0,0,0,0,0,0,0,0,0};
        SharedPreferences p=a.getSharedPreferences("pypet_library",0);int start=Math.max(0,Math.min(p.getInt("challenge",0),q.length-1));
        TextView progress=new TextView(a);progress.setTextSize(17);r.addView(progress);TextView question=new TextView(a);question.setTextSize(19);question.setPadding(0,20,0,15);r.addView(question);LinearLayout answers=new LinearLayout(a);answers.setOrientation(LinearLayout.VERTICAL);r.addView(answers);
        Runnable[] render=new Runnable[1];final int[] index={start};
        render[0]=()->{progress.setText("Python review challenge "+(index[0]+1)+" / "+q.length+"\nCorrect answers unlock the next challenge automatically.");question.setText("🧠 "+q[index[0]]);answers.removeAllViews();for(int i=0;i<choices[index[0]].length;i++){final int pick=i;Button b=button(a,answers,choices[index[0]][i]);b.setOnClickListener(v->{if(pick==correct[index[0]]){RewardInventory.completeTask(a,"library_challenge_"+index[0],3);if(index[0]<q.length-1){index[0]++;p.edit().putInt("challenge",index[0]).apply();render[0].run();Toast.makeText(a,"✓ Correct! Challenge "+(index[0]+1)+" unlocked.",Toast.LENGTH_SHORT).show();}else{p.edit().putInt("challenge",0).apply();render[0].run();Toast.makeText(a,"🏆 Review set complete! Starting the next practice cycle.",Toast.LENGTH_SHORT).show();}}else Toast.makeText(a,"Not quite. Open the Academy lesson for this concept, then try again.",Toast.LENGTH_SHORT).show();});}};render[0].run();
        back(a,r);
    }
}
