package com.odelly.pypet;

import android.app.Activity;
import android.app.AlertDialog;
import android.graphics.Color;
import android.os.Bundle;
import android.view.Gravity;
import android.view.animation.Animation;
import android.view.animation.ScaleAnimation;
import android.widget.*;
import com.chaquo.python.Python;
import com.chaquo.python.android.AndroidPlatform;
import com.google.android.gms.ads.MobileAds;
import java.util.ArrayList;
import java.util.List;

/** Main Pypet screen: the world is primary; school, care, play and discovery drive development. */
public class MainActivity extends Activity {
    TextView status,rewardStatus,petView,petStats,taskStatus,streakStatus,trophyStatus; EditText editor; Python py; RewardAdManager rewardAdManager; Spinner rewardSpinner; Button earnButton,buyButton; PypetAudio audio; PypetSafetyGuard safety;
    @Override public void onCreate(Bundle state){super.onCreate(state);if(!Python.isStarted())Python.start(new AndroidPlatform(this));py=Python.getInstance();safety=new PypetSafetyGuard(this);audio=new PypetAudio();MobileAds.initialize(this,s->{});rewardAdManager=new RewardAdManager(this);rewardAdManager.preload();
        ScrollView scroll=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,28,28,28);root.setGravity(Gravity.CENTER_HORIZONTAL);scroll.addView(root);
        TextView title=new TextView(this);title.setText("🐾 Pypet World");title.setTextSize(30);title.setTextColor(Color.DKGRAY);root.addView(title);
        status=new TextView(this);status.setText("Welcome to your pet's world!");status.setTextSize(18);status.setGravity(Gravity.CENTER);root.addView(status);
        PetEvolutionManager.PetVariant pet=PetEvolutionManager.current(this);petView=new TextView(this);petView.setText(pet.emoji+"\n"+PetEvolutionManager.name(this));petView.setTextSize(64);petView.setGravity(Gravity.CENTER);root.addView(petView,new LinearLayout.LayoutParams(-1,190));safety.suppressHaptics(petView);animatePet();
        petStats=new TextView(this);petStats.setGravity(Gravity.CENTER);root.addView(petStats);refreshPet();
        LinearLayout actions=new LinearLayout(this);Button feed=button("🍎 Feed"),care=button("🧼 Care"),play=button("🎾 Play"),learn=button("📚 Learn");actions.addView(feed);actions.addView(care);actions.addView(play);actions.addView(learn);root.addView(actions);for(Button b:new Button[]{feed,care,play,learn})safety.suppressHaptics(b);
        LinearLayout worldActions=new LinearLayout(this);Button world=button("🌎 World"),school=button("🏫 School"),hatchery=button("🥚 Hatchery");worldActions.addView(world);worldActions.addView(school);worldActions.addView(hatchery);root.addView(worldActions);for(Button b:new Button[]{world,school,hatchery})safety.suppressHaptics(b);world.setOnClickListener(v->PetWorldView.show(this));school.setOnClickListener(v->PypetSchoolView.show(this));hatchery.setOnClickListener(v->PypetHatcheryView.show(this));
        Button music=button("♫ Music: ON");root.addView(music);music.setOnClickListener(v->{audio.setEnabled(!audio.isEnabled());music.setText(audio.isEnabled()?"♫ Music: ON":"♫ Music: OFF");if(audio.isEnabled())audio.start();});safety.suppressHaptics(music);audio.start();
        Button motion=button(safety.reducedMotion()?"Animation: OFF":"Animation: ON");root.addView(motion);motion.setOnClickListener(v->{safety.setReducedMotion(!safety.reducedMotion());motion.setText(safety.reducedMotion()?"Animation: OFF":"Animation: ON");petView.clearAnimation();status.setText(safety.reducedMotion()?"Reduced-motion mode enabled.":"Gentle animation enabled.");if(!safety.reducedMotion())animatePet();});safety.suppressHaptics(motion);
        TextView safetyNote=new TextView(this);safetyNote.setText("Safety mode: no intentional flashing, strobing, screen shake, rapid animation, or reward haptics. Animation can be turned off.");root.addView(safetyNote);
        root.addView(sectionTitle("🧬 Pet Development"));TextView evolutionInfo=new TextView(this);evolutionInfo.setText("Every egg starts a random lineage. Evolution quality favors ALL development areas equally: food/nutrition, health, care, happiness, play, school, Python learning, exploration and routines. Rare variants are rolled separately within each lineage.");root.addView(evolutionInfo);
        editor=new EditText(this);editor.setGravity(Gravity.TOP|Gravity.START);editor.setText("answer = 2 + 3\nprint(answer)");editor.setHint("Optional Python practice outside school...");editor.setMinLines(6);root.addView(editor);Button run=button("Run Practice");root.addView(run);safety.suppressHaptics(run);
        root.addView(sectionTitle("🏆 Trophies & Streak"));streakStatus=new TextView(this);trophyStatus=new TextView(this);root.addView(streakStatus);root.addView(trophyStatus);Button trophyButton=button("View Trophy Cabinet");root.addView(trophyButton);safety.suppressHaptics(trophyButton);trophyButton.setOnClickListener(v->showTrophies());
        root.addView(sectionTitle("✨ Treasure Trove"));TextView treasureInfo=new TextView(this);treasureInfo.setText("Optional cosmetic treasures for your Pypet world. Core pets, school, learning and care remain available without purchase.");root.addView(treasureInfo);Button treasureStore=button("✨ Open Treasure Trove");root.addView(treasureStore);treasureStore.setOnClickListener(v->TreasureStore.show(this));safety.suppressHaptics(treasureStore);
        root.addView(sectionTitle("🪙 Pypet Coins & World Collection"));TextView coinExplanation=new TextView(this);coinExplanation.setText("Earn coins by caring, learning, playing, maintaining streaks and optionally watching rewarded ads. Coins buy cosmetic world items and never unlock essential care or learning.");root.addView(coinExplanation);rewardStatus=new TextView(this);root.addView(rewardStatus);
        root.addView(sectionTitle("Today's Activities"));taskStatus=new TextView(this);taskStatus.setText("Care, play and learn to help your pet grow.");root.addView(taskStatus);Button feedTask=button("Care for pet • +10 coins"),learnTask=button("Complete Python lesson • +25 coins"),playTask=button("Play with pet • +10 coins");root.addView(feedTask);root.addView(learnTask);root.addView(playTask);for(Button b:new Button[]{feedTask,learnTask,playTask})safety.suppressHaptics(b);feedTask.setOnClickListener(v->carePet(10));learnTask.setOnClickListener(v->learnPet(25));playTask.setOnClickListener(v->playPet(10));
        root.addView(sectionTitle("🎁 Earnable World Rewards"));TextView rewardExplanation=new TextView(this);rewardExplanation.setText("Choose a cosmetic item and spend earned Pypet Coins. Watching an ad is always optional.");root.addView(rewardExplanation);earnButton=button("Watch optional ad: +"+RewardAdManager.COINS_PER_REWARDED_AD+" Pypet Coins");root.addView(earnButton);safety.suppressHaptics(earnButton);List<String> rewardNames=new ArrayList<>();for(RewardCatalog.Item item:RewardCatalog.all())rewardNames.add(item.name+" — "+item.priceCoins+" Pypet Coins ["+item.tier+"]");rewardSpinner=new Spinner(this);rewardSpinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,rewardNames));root.addView(rewardSpinner);buyButton=button("Unlock selected reward");root.addView(buyButton);safety.suppressHaptics(buyButton);TextView policyNote=new TextView(this);policyNote.setText("Coins and earned cosmetics are local to this game profile and non-transferable. No task requires an advertisement or payment.");root.addView(policyNote);
        refreshRewardStatus();refreshAchievementStatus();
        feed.setOnClickListener(v->feedPet());care.setOnClickListener(v->carePet(10));play.setOnClickListener(v->playPet(10));learn.setOnClickListener(v->learnPet(25));run.setOnClickListener(v->runCode());earnButton.setOnClickListener(v->earnCoins());buyButton.setOnClickListener(v->purchaseSelectedItem());setContentView(scroll);
    }
    private void feedPet(){PetEvolutionManager.PetFood f=PetEvolutionManager.foods().get(0);PetEvolutionManager.feed(this,f);status.setText(PetEvolutionManager.name(this)+" loved the "+f.name+"!");audio.petSound(330);refreshAll();animatePet();}
    private void carePet(int coins){PetEvolutionManager.performCare(this);if(RewardInventory.completeTask(this,"care_pip",coins))PypetAchievementManager.recordDailyActivity(this);status.setText("🧼 "+PetEvolutionManager.name(this)+" feels cared for!");refreshAll();audio.petSound(392);animatePet();}
    private void playPet(int coins){PetEvolutionManager.playWith(this);if(RewardInventory.completeTask(this,"play_pip",coins))PypetAchievementManager.recordDailyActivity(this);status.setText("🎾 "+PetEvolutionManager.name(this)+" had a great play session!");refreshAll();audio.petSound(440);animatePet();}
    private void learnPet(int coins){PetEvolutionManager.completeLesson(this);if(RewardInventory.completeTask(this,"python_lesson",coins)){int streak=PypetAchievementManager.recordDailyActivity(this);PypetAchievementManager.awardTrophy(this,"first_step",10);if(PetEvolutionManager.lessons(this)>=1)PypetAchievementManager.awardTrophy(this,"python_starter",25);if(PypetAchievementManager.awardStreakMilestone(this,streak))status.setText("🏆 Streak evolution boost! Day "+streak+".");else status.setText("📚 Lesson complete! "+PetEvolutionManager.name(this)+" learned with you.");}else status.setText("📚 Lesson practice complete!");refreshAll();audio.petSound(523);animatePet();}
    private void refreshPet(){PetEvolutionManager.PetVariant p=PetEvolutionManager.current(this);petView.setText(p.emoji+"\n"+PetEvolutionManager.name(this));petStats.setText(p.displayName+" • Level "+p.level+"\n❤️ Health "+PetEvolutionManager.health(this)+"%   🍖 Hunger "+PetEvolutionManager.hunger(this)+"%   😊 Happiness "+PetEvolutionManager.happiness(this)+"%\n📚 Lessons "+PetEvolutionManager.lessons(this)+"   🎾 Play "+PetEvolutionManager.play(this)+"   🧼 Care "+PetEvolutionManager.care(this)+"\n🏫 School "+PetEvolutionManager.school(this)+"   🌎 Explore "+PetEvolutionManager.explore(this)+"   🔥 Routine "+PetEvolutionManager.routine(this)+"\n⭐ Balanced evolution potential: "+PetEvolutionManager.balancedDevelopmentScore(this)+"%   🧬 Evolutions: "+PetEvolutionManager.evolutionCount(this));}
    private void refreshAll(){refreshPet();refreshRewardStatus();refreshAchievementStatus();}
    private void animatePet(){if(petView==null||!safety.allowAnimation())return;ScaleAnimation b=new ScaleAnimation(.98f,1.02f,.98f,1.02f,Animation.RELATIVE_TO_SELF,.5f,Animation.RELATIVE_TO_SELF,1f);b.setDuration(safety.safeAnimationDuration(750));b.setRepeatCount(1);b.setRepeatMode(Animation.REVERSE);petView.startAnimation(b);}
    private TextView sectionTitle(String text){TextView v=new TextView(this);v.setText(text);v.setTextSize(22);v.setTextColor(Color.DKGRAY);v.setPadding(0,24,0,8);return v;}private Button button(String text){Button b=new Button(this);b.setText(text);return b;}
    private void refreshAchievementStatus(){streakStatus.setText("🔥 Current streak: "+PypetAchievementManager.streak(this)+" days • Best: "+PypetAchievementManager.bestStreak(this));trophyStatus.setText("🏆 Trophies earned: "+PypetAchievementManager.trophyCount(this)+" / "+PypetAchievementManager.trophies().length);}
    private void showTrophies(){StringBuilder s=new StringBuilder();for(PypetAchievementManager.Trophy t:PypetAchievementManager.trophies())s.append(PypetAchievementManager.hasTrophy(this,t.id)?"🏆 ":"🔒 ").append(t.name).append(" — ").append(t.description).append(" (+").append(t.coins).append(" coins)\n\n");new AlertDialog.Builder(this).setTitle("🏆 Pypet Trophy Cabinet").setMessage(s.toString()).setPositiveButton("Close",null).show();}
    private void earnCoins(){earnButton.setEnabled(false);rewardAdManager.show(this,new RewardAdManager.RewardListener(){public void onCoinsGranted(int coins){refreshRewardStatus();status.setText("You earned "+coins+" Pypet Coins.");earnButton.setEnabled(true);}public void onAdUnavailable(String message){status.setText(message);earnButton.setEnabled(true);}});}
    private void purchaseSelectedItem(){RewardCatalog.Item item=RewardCatalog.all().get(rewardSpinner.getSelectedItemPosition());if(RewardInventory.owns(this,item.id)){status.setText("You already own "+item.name+".");return;}int balance=RewardInventory.coins(this);if(balance<item.priceCoins){new AlertDialog.Builder(this).setTitle("Not enough Pypet Coins").setMessage(item.name+" costs "+item.priceCoins+" coins. You have "+balance+".").setPositiveButton("Earn Coins",(d,w)->earnCoins()).setNegativeButton("Cancel",null).show();return;}new AlertDialog.Builder(this).setTitle("Unlock "+item.name+"?").setMessage(item.description+"\n\nPrice: "+item.priceCoins+" Pypet Coins.").setPositiveButton("Unlock",(d,w)->{if(RewardInventory.purchase(this,item.id)){try{py.getModule("world_api").callAttr("place_exclusive_item",item.id,"home");}catch(Exception ignored){}refreshRewardStatus();if(RewardInventory.count(this)>=5)PypetAchievementManager.awardTrophy(this,"world_builder",100);refreshAchievementStatus();status.setText(item.name+" has been added to your world.");}else status.setText("Purchase could not be completed.");}).setNegativeButton("No thanks",null).show();}
    private void refreshRewardStatus(){rewardStatus.setText("Pypet Coins: "+RewardInventory.coins(this)+" | World items: "+RewardInventory.count(this)+" / "+RewardCatalog.all().size());}
    private void runCode(){try{String result=py.getModule("pypet_engine").callAttr("run_lesson",editor.getText().toString()).toString();PetEvolutionManager.completeLesson(this);status.setText(result+"\n🐾 "+PetEvolutionManager.name(this)+" learned too!");audio.petSound(523);refreshAll();animatePet();}catch(Exception e){status.setText("Practice error: "+e.getMessage());audio.petSound(196);}}
    @Override protected void onPause(){super.onPause();audio.stop();}@Override protected void onResume(){super.onResume();if(audio!=null&&audio.isEnabled())audio.start();}@Override protected void onDestroy(){audio.stop();super.onDestroy();}
}
