plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}

android {
    namespace 'com.odelly.pypet'
    compileSdk 35

    defaultConfig {
        applicationId 'com.odelly.pypet'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '0.1.0-alpha'
    }
}

chaquopy {
    defaultConfig {
        version = '3.13'
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-ads:25.4.0'
}
